services:
  - type: web
    name: smart_health_api
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerfile:
      buildArgs: []
    buildCommand: []
    startCommand: []
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
